In [ ]:
from google.colab import drive

drive.mount('/content/drive');

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import scipy.stats.distributions as dist

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

# Example 1

**The population proportion of Ireland having heart disease is 49%. Are more people suffering from heart disease in the US**

In [ ]:
heart_dataset = '/content/drive/MyDrive/FDS Practical/heart.csv'

df = pd.read_csv(heart_dataset)
df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   52    1   0       125   212    0  ...      0      1.0      2   2     3       0
1   53    1   0       140   203    1  ...      1      3.1      0   0     3       0
2   70    1   0       145   174    0  ...      1      2.6      0   0     3       0
3   61    1   0       148   203    0  ...      0      0.0      2   1     3       0
4   62    0   0       138   294    1  ...      0      1.9      1   3     2       0

[5 rows x 14 columns]

In [ ]:
# null hypothesis => p0 = 0.49
# alternative hypothesis => p > 0.49

In [ ]:
# The "target" field refers to the presence of heart disease in the patient. 
# It is integer valued 0 = no disease and 1 = disease.

p_us = len(df[df['target'] == 1])/ len(df) # calculating population proportion
p_us

0.5131707317073171

In [ ]:
# The population proportion of the sample having heart disease is 0.51 or 51%.

# Perform hypothesis test

se = np.sqrt(0.49 * (1 - 0.49) / len(df)) # calculating standard error

be = p_us # best estimate 
he =  0.49 # hypothesized estimate
test_stat = (be - he)/se # calculating test statistics

test_stat

1.483947557138075

In [ ]:
pvalue = 2 * dist.norm.cdf(-np.abs(test_stat)) # calculating p-value

pvalue

0.13782283387121433

Consider the significance level alpha to be 5% or 0.05. A significance level of 5% or less means that there is a probability of 95% or greater that the results are not random.

Here p-value is bigger than our considered significance level of 0.05. So, we cannot reject the null hypothesis. That means there is no significant difference in population proportion having heart disease in Ireland and the US.

# Example 2

**Population proportion of students who have taken portuguese subject and has access to internet is 90%. Do more students who have taken math subject have access to the internet?**

In [ ]:
# null hypothesis => p0 = 0.90
# alternative hypothesis => p > 0.90

In [ ]:
math_students_dataset = '/content/drive/MyDrive/FDS Practical/student-mat.csv'

df = pd.read_csv(math_students_dataset)
df.head()

  school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [ ]:
p_internet = len(df[df['internet'] == 'yes'])/len(df)
p_internet

0.8329113924050633

In [ ]:
se = np.sqrt(0.90 * (1 - 0.90) / len(df)) # calculating standard error

be = p_internet # best estimate 
he =  0.90 # hypothesized estimate
test_stat = (be - he)/se # calculating test statistics

test_stat

-4.444532347935213

In [ ]:
pvalue = 2 * dist.norm.cdf(-np.abs(test_stat)) # calculating p-value

pvalue

8.808325492884064e-06

In [ ]:
if pvalue < 0.05:    # alpha value is 0.05 or 5%
   print("we are rejecting null hypothesis")
else:
  print("we are accepting null hypothesis")

we are rejecting null hypothesis