In [ ]:
import pandas as pd
import numpy as np
%cd ..
from google.colab import drive
drive.mount('/content/gdrive')

/
Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
location1="/content/gdrive/MyDrive/student-mat.csv"
location1

'/content/gdrive/MyDrive/student-mat.csv'

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/student-mat.csv')
df.head(3)

  school sex  age address famsize Pstatus  ...  Walc  health absences G1 G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6  5  6   6
1     GP   F   17       U     GT3       T  ...     1       3        4  5  5   6
2     GP   F   15       U     LE3       T  ...     3       3       10  7  8  10

[3 rows x 33 columns]

In [ ]:
len(df)

395

In [ ]:
df['grade_A'] = np.where(df['G3']*5 >= 80, 1, 0)

In [ ]:
df['high_absenses'] = np.where(df['absences'] >= 10, 1, 0)

In [ ]:
df['count'] = 1

In [ ]:
df = df[['grade_A','high_absenses','count']]
df.head()

   grade_A  high_absenses  count
0        0              0      1
1        0              0      1
2        0              1      1
3        0              0      1
4        0              0      1

In [ ]:
pd.pivot_table(
    df, 
    values='count', 
    index=['grade_A'], 
    columns=['high_absenses'], 
    aggfunc=np.size, 
    fill_value=0
)

high_absenses    0   1
grade_A
0              277  78
1               35   5